apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-marvelous-storage
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod

spec:
  containers:
  - image: alpine
    command: ["/bin/sh", "-c", "echo hello > /vol/test && ls -l /vol && cat /vol/test; sleep 100"]
    name: container
    volumeMounts:
    - mountPath: /vol
      name: volume
  volumes:
  - name: volume
    persistentVolumeClaim:
      claimName: claim
      