apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: date-log
spec:
  serviceName: date-log
  selector:
    matchLabels:
      app: date-log
  replicas: 3
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: date-log
    spec:
      containers:
      - name: logger
        image: alpine
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "(echo '=== START ===' && while true; do sleep 1 && date; done) | tee -a /vol/logs"]
        volumeMounts:
        - mountPath: /vol
          name: data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: my-marvelous-storage
      resources:
        requests:
          storage: 100Mi
