apiVersion: storage.k8s.io/v1
kind: StorageClass
provisioner: dothill.csi.enix.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
metadata:
  name: my-marvelous-storage
parameters:
  csi.storage.k8s.io/provisioner-secret-name: dothill-api
  csi.storage.k8s.io/provisioner-secret-namespace: dothill-system
  csi.storage.k8s.io/controller-publish-secret-name: dothill-api
  csi.storage.k8s.io/controller-publish-secret-namespace: dothill-system
  csi.storage.k8s.io/controller-expand-secret-name: dothill-api
  csi.storage.k8s.io/controller-expand-secret-namespace: dothill-system
  fsType: ext4
  iqn: iqn.2015-11.com.hpe:storage.msa2050.2002518b4c
  pool: A
  portals: 10.0.0.24,10.0.0.25
---
apiVersion: v1
kind: Secret
metadata:
  name: dothill-api
  namespace: dothill-system
type: Opaque
data:
  apiAddress: aHR0cHM6Ly8xMC4wLjAuNDI=
  username: am9obi5kb2U=
  password: bXktU0BmZStwYXNzdzByZCE=
