apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: systems-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: systems-storageclass
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - image: seagatecsi/mksimple
    command: ["/bin/sh", "-c", "while sleep 60; do echo hello > /vol/test && ls -l /vol && cat /vol/test && rm /vol/test; done"]
    name: test-pod-container
    volumeMounts:
    - mountPath: /vol
      name: volume
    ports:
    - containerPort: 8080
  volumes:
  - name: volume
    persistentVolumeClaim:
      claimName: systems-pvc
