stages:
  - build
  - release

build dirty docker image:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - apk add --update make git
    - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
  script:
    - VERSION=dirty make push
  rules:
    - if: $CI_COMMIT_TAG == null && $CI_COMMIT_MESSAGE !~ /^chore\(release\):/

build and push:
  stage: release
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - apk add --update make
    - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
  script:
    - VERSION="$CI_COMMIT_TAG" make push
    - docker tag "seagate/seagate-csi:$CI_COMMIT_TAG" seagate/seagate-csi
    - docker push seagate/seagate-csi
  only:
    - tags

push helm chart:
  stage: release
  image: golang:alpine3.12
  before_script:
    - GO111MODULE=on go get github.com/norwoodj/helm-docs/cmd/helm-docs
    - apk add --update git openssh
    - eval $(ssh-agent -s)
    - cat "$GITHUB_DEPLOY_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - git config --global user.email "monkeynator@seagate.io"
    - git config --global user.name "Monkeynator"
  script:
    - git clone --single-branch --branch master git@github.com:seagate/helm-charts.git
    - rm -rf ./helm-charts/charts/seagate-csi
    - cp ./LICENSE ./helm/csi-charts/
    - cp -R ./helm/csi-charts ./helm-charts/charts/seagate-csi
    - cd ./helm-charts/charts/seagate-csi
    - >
      sed -i
      -e "s/version: 0\.0\.0-DIRTY/version: ${CI_COMMIT_TAG:1}/g"
      -e "s/appVersion: 0\.0\.0-DIRTY/appVersion: $CI_COMMIT_TAG/g"
      -e "s/image: seagate\/seagate-csi:0\.0\.0-DIRTY/image: seagate\/seagate-csi:$CI_COMMIT_TAG/g"
      ./Chart.yaml
    - helm-docs
    - rm ./README.md.gotmpl
    - git add --all
    - >
      git commit -m "bump(seagate-csi): bump chart version to $CI_COMMIT_TAG"
    - git push --set-upstream origin master
  only:
    - tags

release-candidate:
  stage: release
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - apk add --update make
    - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
  script:
    - VERSION="rc-$CI_PIPELINE_ID" make push
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_TAG == null && $CI_COMMIT_MESSAGE !~ /^chore\(release\):/

semantic-release:
  stage: release
  image: seagate/semantic-release:gitlab
  script:
    - npx semantic-release --ci
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_TAG == null && $CI_COMMIT_MESSAGE !~ /^chore\(release\):/
      when: manual
