stages:
  - build
  - release

build dirty docker image:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - apk add --update make git
    - docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - VERSION=dirty make push
  except:
    - tags

build and push:
  stage: release
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - apk add --update make
    - docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - VERSION="${CI_COMMIT_TAG:1}" make push
  only:
    - tags

push helm chart:
  stage: release
  image: alpine
  before_script:
    - apk add --update git openssh
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - chmod 400 $GITHUB_DEPLOY_KEY
    - git config --global user.email "monkeynator@enix.io"
    - git config --global user.name "Monkeynator"
  script:
    - >
      ssh-agent sh -c "ssh-add '$GITHUB_DEPLOY_KEY';
      yes yes | git clone --single-branch --branch master git@github.com:enix/helm-charts.git"
    - rm -rf ./helm-charts/charts/dothill-provisioner
    - cp -R ./helm/dothill-provisioner ./helm-charts/charts/dothill-provisioner
    - cd ./helm-charts
    - sed -i -e "s/0\.0\.0-DIRTY/$CI_COMMIT_TAG/g" ./charts/dothill-provisioner/Chart.yaml
    - git add --all
    - >
      git commit -m "bump(dothill-provisioner): bump chart version to $CI_COMMIT_TAG"
    - >
      ssh-agent sh -c "ssh-add '$GITHUB_DEPLOY_KEY';
      git push --set-upstream origin master"
  only:
    - tags

release-candidate:
  stage: release
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - apk add --update make
    - docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - VERSION="rc-$CI_PIPELINE_ID" make push
  only:
    - master
  except:
    - tags

semantic-release:
  stage: release
  image: enix/semantic-release:gitlab
  script:
    - npx semantic-release --ci
  when: manual
  only:
    - master
  except:
    - tags
