stages:
  - test
  - release

build dirty docker image:
  stage: test
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - apk add --update make
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - echo $CI_COMMIT_TAG
    - VERSION="$(git log | head -n 1 | awk '{ print $2 }')" make push
  except:
    - tags

build and push:
  stage: release
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - apk add --update make
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - VERSION="${CI_COMMIT_TAG:1}" make push
  only:
    - tags

semantic-release:
  stage: release
  image: enix/semantic-release:gitlab
  script:
    - npx semantic-release --ci
  only:
    - master
  except:
    - tags
