plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/gitlab'
    - gitlabUrl: 'https://gitlab.enix.io'
  - - '@semantic-release/changelog'
    - changelogFile: 'docs/CHANGELOG.md'
  - - '@semantic-release/git'
    - assets: 'docs/CHANGELOG.md'
