[[constraint]]
  name = "github.com/enix/dothill-api-go"
  version = "1.3.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.15.4"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.0"

[[constraint]]
  name = "k8s.io/klog"
  version = "0.1.0"

[[constraint]]
  name = "sigs.k8s.io/sig-storage-lib-external-provisioner"
  version = "3.1.0"

[[constraint]]
  name = "github.com/kubernetes-csi/external-resizer"
  version = "0.3.0"

[[override]]
  name = "k8s.io/csi-translation-lib"
  version = "kubernetes-1.15.4"

[prune]
  go-tests = true
  unused-packages = true
