apiVersion: v2
name: dothill-csi
version: 0.0.0-DIRTY
appVersion: 0.0.0-DIRTY
description: A dynamic persistent volume (PV) provisioner for Dothill AssuredSAN based storage systems.
type: application
home: https://github.com/Seagate/seagate-exos-x-csi
sources:
  - https://github.com/Seagate/seagate-exos-x-csi/tree/main/helm/dothill-csi
keywords:
  - storage
  - iscsi
  - plugin
  - csi
maintainers:
  - name: Seagate
    email: contact@enix.fr
    url: https://github.com/Seagate
  - name: Joe Skazinski
    email: joseph.skazinski@seagate.com
annotations:
  artifacthub.io/images: |
    - name: dothill-csi
      image: docker.io/seagatecsi/dothill-csi
