apiVersion: v2
name: exosx-csi
version: 0.0.0-DIRTY
appVersion: 0.0.0-DIRTY
description: A dynamic persistent volume (PV) provisioner for Seagate Exos X storage systems.
type: application
home: https://github.com/Seagate/seagate-exos-x-csi
sources:
  - https://github.com/Seagate/seagate-exos-x-csi/tree/main/helm/exosx-csi
keywords:
  - storage
  - iscsi
  - plugin
  - csi
maintainers:
  - name: Seagate
    url: https://github.com/Seagate
  - name: Joe Skazinski
    email: joseph.skazinski@seagate.com
annotations:
  artifacthub.io/images: |
    - name: exosx-csi
      image: docker.io/seagatecsi/seagate-exosx-csi
