---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dothill-node

spec:
  selector:
    matchLabels:
      name: dothill-node
  template:
    metadata:
      labels:
        name: dothill-node
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        # - name: dothill-node
        #   image: docker-registry.enix.io/enix/dothill-provisioner:rc
        #   command:
        #     - dothill-node
        #     - -bind=unix:///csi/csi.sock
        #   lifecycle:
        #     preStop:
        #       exec:
        #         command: ["/bin/sh", "-c", "rm -rf /csi/csi.sock"]
        #   volumeMounts:
        #     - name: plugin-dir
        #       mountPath: /csi
        - name: driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.0.2
          command:
            - sh
            - -c
            - mkdir -p /csi/dev && /node-driver-registrar --v=5 --csi-address=/csi/csi.sock --kubelet-registration-path=/var/lib/kubelet/plugins/dothill.csi.enix.io/csi.sock
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/dothill.csi.enix.io /registration/dothill.csi.enix.io-reg.sock"]
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        # - name: tcp-node
        #   image: alpine/socat
        #   command:
        #     - socat
        #     - -v
        #     - UNIX-LISTEN:/csi/csi.sock,reuseaddr,fork
        #     - TCP:xx.xx.xx.xx:xxxx
        #   volumeMounts:
        #     - name: plugin-dir
        #       mountPath: /csi
      volumes:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/dothill.csi.enix.io
            type: DirectoryOrCreate
