---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dothill-controller

spec:
  replicas: 1
  selector:
    matchLabels:
      app: dothill-controller
  template:
    metadata:
      labels:
        app: dothill-controller
    spec:
      serviceAccount: csi-provisioner
      containers:
        # - name: dothill-controller
        #   image: docker-registry.enix.io/enix/dothill-provisioner:rc
        #   volumeMounts:
        #     - name: socket-dir
        #       mountPath: /csi
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:canary
          args:
            - --csi-address=/csi/csi.sock
            - --enable-leader-election
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:canary
          args:
            - --csi-address=/csi/csi.sock
            - --leader-election
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: tcp-controller
          image: alpine/socat
          command:
            - socat
            - -v
            - UNIX-LISTEN:/csi/csi.sock,reuseaddr,fork
            - TCP:10.14.255.81:10000
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir:
