---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dothill-controller-server
  namespace: kube-system

spec:
  replicas: 1
  selector:
    matchLabels:
      app: dothill-controller-server
  template:
    metadata:
      labels:
        app: dothill-controller-server
    spec:
      serviceAccount: csi-provisioner
      containers:
        - name: dothill-controller
          image: docker-registry.enix.io/enix/dothill-provisioner:rc
          command:
            - dothill-controller
            - -bind=unix:///csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:canary
          args:
            - --csi-address=/csi/csi.sock
            - --enable-leader-election
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:canary
          args:
            - --csi-address=/csi/csi.sock
            - --leader-election
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        # - name: csi-resizer
        #   image: quay.io/k8scsi/csi-resizer:canary
        #   args:
        #     - --csi-address=/csi/csi.sock
        #     - --leader-election
        #   imagePullPolicy: IfNotPresent
        #   volumeMounts:
        #     - name: socket-dir
        #       mountPath: /csi
        # - name: tcp-controller
        #   image: alpine/socat
        #   command:
        #     - socat
        #     - -v
        #     - UNIX-LISTEN:/csi/csi.sock,reuseaddr,fork
        #     - TCP:10.14.145.17:10000
        #   volumeMounts:
        #     - name: socket-dir
        #       mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir:
