apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dothill-provisioner
  namespace: kube-system

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dothill-provisioner
subjects:
  - kind: ServiceAccount
    name: dothill-provisioner
