apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: msa-provisioner
  namespace: msa-storage

rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "delete"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
