apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: msa-provisioner
  namespace: msa-storage

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: msa-provisioner
subjects:
  - kind: ServiceAccount
    name: msa-provisioner
