apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-node-server
  labels:
    app.kubernetes.io/version: {{ .Chart.Version }}
{{ include "dothill.labels" . | indent 4 }}

spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}-node-server
{{ include "dothill.labels" . | indent 6 }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-node-server
{{ include "dothill.labels" . | indent 8 }}
    spec:
      {{ if .Values.pspAdmissionControllerEnabled }}serviceAccount: csi-node-registrar{{ end }}
      hostNetwork: true
      initContainers:
        - name: generate-unique-initiator-name
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          command:
            - sh
            - -c
            - >
              [ -f /host/iscsi/initiatorname.iscsi ] || (
                cp /etc/iscsi/* /host/iscsi &&
                sed -re "s/(InitiatorName=).*/\1$(iscsi-iname -p iqn.2013-10.io.enix)/" /etc/iscsi/initiatorname.iscsi > /host/iscsi/initiatorname.iscsi
              )
          volumeMounts:
            - name: iscsi-dir
              mountPath: /host/iscsi
      containers:
        - name: {{ .Release.Name }}-node
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          command:
            - dothill-node
            - -kubeletpath={{ .Values.kubeletPath }}
            - -bind=unix://{{ .Values.kubeletPath }}/plugins/dothill.csi.enix.io/csi.sock
{{- include "dothill.extraArgs" .Values.node | indent 10 }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: device-dir
              mountPath: /dev
            - name: iscsi-dir
              mountPath: /etc/iscsi
            - name: plugin-dir
              mountPath: {{ .Values.kubeletPath }}/plugins/dothill.csi.enix.io
            - name: mountpoint-dir
              mountPath: {{ .Values.kubeletPath }}/pods
              mountPropagation: Bidirectional
          ports:
          - containerPort: 9808
            name: healthz
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
        - name: iscsid
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          command:
            - iscsid
            - --foreground
          securityContext:
            privileged: true
          volumeMounts:
            - name: device-dir
              mountPath: /dev
            - name: iscsi-dir
              mountPath: /etc/iscsi
            - name: plugin-dir
              mountPath: {{ .Values.kubeletPath }}/plugins/dothill.csi.enix.io
            - name: mountpoint-dir
              mountPath: {{ .Values.kubeletPath }}/pods
              mountPropagation: Bidirectional
        - name: liveness-probe
          image: quay.io/k8scsi/livenessprobe:v1.1.0
          args:
            - --csi-address=/csi/csi.sock
{{- include "dothill.extraArgs" .Values.nodeLivenessProbe | indent 10 }}
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
        - name: driver-registrar
          image: {{ .Values.csiNodeRegistrar.image.repository }}:{{ .Values.csiNodeRegistrar.image.tag }}
          args:
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path={{ .Values.kubeletPath }}/plugins/dothill.csi.enix.io/csi.sock
{{- include "dothill.extraArgs" .Values.csiNodeRegistrar | indent 10 }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/dothill.csi.enix.io /registration/dothill.csi.enix.io-reg.sock"]
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
      volumes:
        - name: device-dir
          hostPath:
            path: /dev
        - name: registration-dir
          hostPath:
            path: {{ .Values.kubeletPath }}/plugins_registry/
        - name: iscsi-dir
          hostPath:
            path: /etc/iscsi
        - name: mountpoint-dir
          hostPath:
            path: {{ .Values.kubeletPath }}/pods
        - name: plugin-dir
          hostPath:
            path: {{ .Values.kubeletPath }}/plugins/dothill.csi.enix.io
            type: DirectoryOrCreate
