name: Release

on:
  push:
    branches:
      - main

jobs:

  release:
    name: Update Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: ridedott/release-me-action@master
      with:
        release-branches: '["main"]'
        disable-changelog: false

    - name: Fetch latest release version
      id: fetch-latest-release
      uses: reloc8/action-latest-release-version@1.0.0

    - name: Output
      run: echo "released version is ${{ steps.fetch-latest-release.outputs.latest-release }}"
